name: audio_router
description: Route audio per-app to different outputs. Simple. Clean.
publish_to: 'none'
version: 1.2.24+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  provider: ^6.1.1
  shared_preferences: ^2.5.5
  system_tray: ^2.0.3
  window_manager: ^0.3.8
  collection: ^1.18.0
  google_fonts: ^6.2.1
  fluent_ui: ^4.9.0
  macos_ui: ^2.0.0
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  package_info_plus: ^9.0.0
  flutter_markdown: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/tray_icon.ico
    - assets/tray_icon.png
